apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      nodePort: {{ .Values.gateway.service.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    {{- include "gitlab-devops-exam.labels" . | nindent 4 }}
    app.kubernetes.io/name: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  template:
    metadata:
      labels:
        {{- include "gitlab-devops-exam.labels" . | nindent 8 }}
        app.kubernetes.io/name: gateway
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.images.gateway.repository }}:{{ .Values.images.gateway.tag }}"
          imagePullPolicy: {{ .Values.images.gateway.pullPolicy }}
          command: ["uvicorn"]
          args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: USERS_SERVICE_URL
              value: http://users:8000
            - name: ORDERS_SERVICE_URL
              value: http://orders:8000
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5

