apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      nodePort: {{ .Values.gateway.service.nodePort }}
