{{- range $name, $config := .Values.internalServices }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - name: http
      port: {{ $config.service.port }}
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
          imagePullPolicy: {{ $config.image.pullPolicy }}
          command: ["uvicorn"]
          args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5

{{- end }}