apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: users
  ports:
    - name: http
      port: {{ .Values.users.service.port }}
      targetPort: http
